CREATE DATABASE projectsdatabase;

CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''), 
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done boolean,
    projectId integer REFERENCES projects(id)
);

-- Insert to projects
INSERT INTO projects(name, priority, description, deliverydate) 
VALUES ('Make a web APp', 1, 'Using JavaScript', '2020-02-12');

INSERT INTO projects(name, priority, description, deliverydate) 
VALUES ('Make a web desktop', 3, 'Using java', '2018-02-12');

INSERT INTO projects(name, priority, description, deliverydate) 
VALUES ('Make a web APp', 1, 'Using Kotlin', '2005-02-12');

-- Insert to tasks
INSERT INTO tasks(name, done, projectId)
VALUES ('Dowland Vuejs', false, 1);

INSERT INTO tasks(name, done, projectId)
VALUES ('Dowland netbeans', false, 2);

INSERT INTO tasks(name, done, projectId)
VALUES ('Create components', false, 1);